name: Deploy Images to GHCR

env:
    REGISTRY: ghcr.io
    # Will resolve to foundry-rs/foundry
    IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
      push-node-forge-image:
        runs-on: Linux-20.04
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/codekoriko/node20-foundry-nightly-2024-03-06:latest
              docker push ghcr.io/codekoriko/node20-foundry-nightly-2024-03-06:latest
